export const petMock = {
  name: "Pluto",
  type: "dog",
  userId: "123",
  age: 0,
  breed: "test",
  gender: "test",
  color: "test",
  size: "test",
  description: "test",
  trained: false,
  livedInAHouse: [],
  healthState: [""],
  goodWith: [],
  characteristics: [],
  selectedFiles: [],
  selectedCoverIndex: 0,
};
