export const users = [
  {
    id: "655f232ce60f6f81d0693e71",
    _id: "655f232ce60f6f81d0693e71",
    email: "boyan@email.com",
    firstTimeOwner: "",
    password: "password",
    role: "user",
    firstName: "Боян",
    lastName: "К",
    city: "София",
    address: "София",
    zipCode: "1111",
    favorites: [],
    preferences: {
      type: "dog",
      age: "",
      size: "big",
      color: "white",
      gender: "male",
      trained: "",
      livedInAHouse: [],
      goodWith: [
        "travelling",
        "activeLifestyle",
        "quietEnvironment",
        "apartmentLiving",
      ],
      houseConditions: [],
      characteristics: [
        "hygienic",
        "lowShedding",
        "houseTrained",
        "obedient",
        "quiet",
      ],
    },
  },
  {
    id: "655f232ce60f6f81d0693e72",
    _id: "655f232ce60f6f81d0693e72",
    email: "kalina@email.com",
    firstTimeOwner: "",
    password: "password",
    role: "user",
    firstName: "Калина",
    lastName: "А",
    city: "София",
    address: "София",
    zipCode: "1111",
    favorites: [],
    preferences: {
      type: "cat",
      age: "",
      size: "small",
      color: "",
      gender: "female",
      trained: "",
      livedInAHouse: ["withPets", "withYard"],
      goodWith: ["kids"],
      houseConditions: [],
      characteristics: [
        "friendly",
        "playful",
        "affectionate",
        "gentle",
        "energetic",
        "calm",
        "curious",
        "loyal",
        "social",
        "independent",
        "smart",
        "wellBehaved",
        "hygienic",
      ],
    },
  },
  {
    id: "655f232ce60f6f81d0693e73",
    _id: "655f232ce60f6f81d0693e73",
    email: "borisa@email.com",
    firstTimeOwner: "",
    password: "password",
    role: "user",
    firstName: "Бориса",
    lastName: "А",
    city: "София",
    address: "София",
    zipCode: "1111",
    favorites: [],
    preferences: {
      type: "bird",
      age: "",
      size: "small",
      color: "",
      gender: "",
      trained: "",
      livedInAHouse: [],
      goodWith: [
        "strangers",
        "travelling",
        "activeLifestyle",
        "quietEnvironment",
        "apartmentLiving",
      ],
      houseConditions: [],
      characteristics: [
        "independent",
        "smart",
        "wellBehaved",
        "hygienic",
        "lowShedding",
        "houseTrained",
        "obedient",
        "quiet",
        "active",
      ],
    },
  },
];
export const admins = [
  {
    id: "655f232ce60f6f81d0693e74",
    _id: "655f232ce60f6f81d0693e74",
    email: "admin@email.com",
    firstTimeOwner: "",
    password: "password",
    role: "admin",
    firstName: "Симона",
    lastName: "Н",
    city: "София",
    address: "София",
    zipCode: "1111",
    favorites: [],
    preferences: {
      type: "",
      age: "",
      size: "",
      color: "",
      gender: "",
      trained: "",
      livedInAHouse: [],
      goodWith: [],
      houseConditions: [],
      characteristics: [],
    },
  },
];
